import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const CITY = "Bengaluru";

const seedProfiles = [
  {
    email: "aisha.k@campus.edu",
    name: "Aisha Khan",
    age: 21,
    gender: "FEMALE" as const,
    genderPreference: "FEMALE" as const,
    college: "Bengaluru Institute of Technology",
    course: "Computer Science",
    year: 3,
    preferredArea: "Koramangala",
    budgetMin: 12000,
    budgetMax: 18000,
    languages: ["English", "Hindi", "Urdu"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "EARLY_BIRD" as const,
    cleanliness: "VERY_CLEAN" as const,
    pets: false,
    studyHabits: "QUIET" as const,
    interests: ["Reading", "Yoga", "Cooking"],
    bio: "CS student who loves a tidy, quiet home. Early riser, always up for a chai chat.",
  },
  {
    email: "priya.s@campus.edu",
    name: "Priya Sharma",
    age: 22,
    gender: "FEMALE" as const,
    genderPreference: "FEMALE" as const,
    college: "Bengaluru Institute of Technology",
    course: "Design",
    year: 4,
    preferredArea: "Koramangala",
    budgetMin: 13000,
    budgetMax: 19000,
    languages: ["English", "Hindi"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "SOMETIMES" as const,
    sleepSchedule: "EARLY_BIRD" as const,
    cleanliness: "VERY_CLEAN" as const,
    pets: false,
    studyHabits: "QUIET" as const,
    interests: ["Sketching", "Yoga", "Coffee"],
    bio: "Design student, plant mom, into minimalist living.",
  },
  {
    email: "rahul.m@campus.edu",
    name: "Rahul Mehta",
    age: 23,
    gender: "MALE" as const,
    genderPreference: "ANY" as const,
    college: "National College of Engineering",
    course: "Mechanical Engineering",
    year: 4,
    preferredArea: "HSR Layout",
    budgetMin: 10000,
    budgetMax: 15000,
    languages: ["English", "Hindi", "Marathi"],
    foodPreference: "NON_VEG" as const,
    smoking: "SOMETIMES" as const,
    drinking: "REGULARLY" as const,
    sleepSchedule: "NIGHT_OWL" as const,
    cleanliness: "RELAXED" as const,
    pets: true,
    studyHabits: "SOCIAL" as const,
    interests: ["Football", "Gaming", "Music"],
    bio: "Night owl, love hosting friends and playing FIFA till 2am.",
  },
  {
    email: "arjun.v@campus.edu",
    name: "Arjun Verma",
    age: 22,
    gender: "MALE" as const,
    genderPreference: "ANY" as const,
    college: "National College of Engineering",
    course: "Mechanical Engineering",
    year: 3,
    preferredArea: "HSR Layout",
    budgetMin: 9000,
    budgetMax: 14000,
    languages: ["English", "Hindi"],
    foodPreference: "NON_VEG" as const,
    smoking: "SOMETIMES" as const,
    drinking: "REGULARLY" as const,
    sleepSchedule: "NIGHT_OWL" as const,
    cleanliness: "MODERATE" as const,
    pets: true,
    studyHabits: "SOCIAL" as const,
    interests: ["Football", "Gaming", "Movies"],
    bio: "Chill roommate, always down for a match on TV or a late-night snack run.",
  },
  {
    email: "sneha.r@campus.edu",
    name: "Sneha Reddy",
    age: 20,
    gender: "FEMALE" as const,
    genderPreference: "ANY" as const,
    college: "St. Xavier's College",
    course: "Economics",
    year: 2,
    preferredArea: "Indiranagar",
    budgetMin: 15000,
    budgetMax: 22000,
    languages: ["English", "Telugu"],
    foodPreference: "EGGETARIAN" as const,
    smoking: "NEVER" as const,
    drinking: "SOMETIMES" as const,
    sleepSchedule: "FLEXIBLE" as const,
    cleanliness: "MODERATE" as const,
    pets: false,
    studyHabits: "MODERATE" as const,
    interests: ["Photography", "Traveling", "Coffee"],
    bio: "Econ major, love exploring cafes and weekend trips.",
  },
  {
    email: "meera.n@campus.edu",
    name: "Meera Nair",
    age: 21,
    gender: "FEMALE" as const,
    genderPreference: "ANY" as const,
    college: "St. Xavier's College",
    course: "Journalism",
    year: 3,
    preferredArea: "Indiranagar",
    budgetMin: 14000,
    budgetMax: 20000,
    languages: ["English", "Malayalam"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "SOMETIMES" as const,
    sleepSchedule: "FLEXIBLE" as const,
    cleanliness: "MODERATE" as const,
    pets: true,
    studyHabits: "SOCIAL" as const,
    interests: ["Writing", "Traveling", "Photography"],
    bio: "Aspiring journalist, always got a story and a snack to share.",
  },
  {
    email: "karan.j@campus.edu",
    name: "Karan Joshi",
    age: 24,
    gender: "MALE" as const,
    genderPreference: "MALE" as const,
    college: "National College of Engineering",
    course: "Computer Science",
    year: 5,
    preferredArea: "Whitefield",
    budgetMin: 18000,
    budgetMax: 25000,
    languages: ["English", "Hindi", "Gujarati"],
    foodPreference: "VEGAN" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "EARLY_BIRD" as const,
    cleanliness: "VERY_CLEAN" as const,
    pets: false,
    studyHabits: "QUIET" as const,
    interests: ["Fitness", "Reading", "Cooking"],
    bio: "Grad student, gym in the morning, deep work in the evening.",
  },
  {
    email: "vikram.s@campus.edu",
    name: "Vikram Singh",
    age: 23,
    gender: "MALE" as const,
    genderPreference: "MALE" as const,
    college: "National College of Engineering",
    course: "Computer Science",
    year: 4,
    preferredArea: "Whitefield",
    budgetMin: 17000,
    budgetMax: 24000,
    languages: ["English", "Hindi", "Punjabi"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "EARLY_BIRD" as const,
    cleanliness: "VERY_CLEAN" as const,
    pets: false,
    studyHabits: "QUIET" as const,
    interests: ["Fitness", "Coding", "Cooking"],
    bio: "Backend dev, gym rat, and a bit of a clean freak.",
  },
  {
    email: "divya.p@campus.edu",
    name: "Divya Patel",
    age: 20,
    gender: "FEMALE" as const,
    genderPreference: "FEMALE" as const,
    college: "Bengaluru Institute of Technology",
    course: "Biotechnology",
    year: 2,
    preferredArea: "Jayanagar",
    budgetMin: 8000,
    budgetMax: 12000,
    languages: ["English", "Gujarati", "Hindi"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "EARLY_BIRD" as const,
    cleanliness: "VERY_CLEAN" as const,
    pets: false,
    studyHabits: "QUIET" as const,
    interests: ["Reading", "Painting", "Music"],
    bio: "Budget-conscious biotech student, quiet and tidy.",
  },
  {
    email: "ananya.g@campus.edu",
    name: "Ananya Gupta",
    age: 21,
    gender: "FEMALE" as const,
    genderPreference: "FEMALE" as const,
    college: "Bengaluru Institute of Technology",
    course: "Biotechnology",
    year: 3,
    preferredArea: "Jayanagar",
    budgetMin: 9000,
    budgetMax: 13000,
    languages: ["English", "Hindi", "Bengali"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "EARLY_BIRD" as const,
    cleanliness: "VERY_CLEAN" as const,
    pets: false,
    studyHabits: "QUIET" as const,
    interests: ["Reading", "Music", "Baking"],
    bio: "Lab hours are long, so home needs to be calm and clean.",
  },
  {
    email: "ishaan.k@campus.edu",
    name: "Ishaan Kapoor",
    age: 22,
    gender: "MALE" as const,
    genderPreference: "ANY" as const,
    college: "St. Xavier's College",
    course: "Business Administration",
    year: 3,
    preferredArea: "Koramangala",
    budgetMin: 16000,
    budgetMax: 22000,
    languages: ["English", "Hindi"],
    foodPreference: "NON_VEG" as const,
    smoking: "SOMETIMES" as const,
    drinking: "SOMETIMES" as const,
    sleepSchedule: "FLEXIBLE" as const,
    cleanliness: "MODERATE" as const,
    pets: true,
    studyHabits: "MODERATE" as const,
    interests: ["Startups", "Football", "Music"],
    bio: "MBA student building a side hustle, easygoing roommate.",
  },
  {
    email: "farhan.a@campus.edu",
    name: "Farhan Ahmed",
    age: 23,
    gender: "MALE" as const,
    genderPreference: "ANY" as const,
    college: "St. Xavier's College",
    course: "Business Administration",
    year: 4,
    preferredArea: "Koramangala",
    budgetMin: 15000,
    budgetMax: 21000,
    languages: ["English", "Urdu", "Hindi"],
    foodPreference: "NON_VEG" as const,
    smoking: "NEVER" as const,
    drinking: "SOMETIMES" as const,
    sleepSchedule: "FLEXIBLE" as const,
    cleanliness: "MODERATE" as const,
    pets: true,
    studyHabits: "MODERATE" as const,
    interests: ["Startups", "Cricket", "Movies"],
    bio: "Marketing student, cricket on weekends, easy to live with.",
  },
  {
    email: "tanvi.b@campus.edu",
    name: "Tanvi Bhatt",
    age: 19,
    gender: "FEMALE" as const,
    genderPreference: "ANY" as const,
    college: "National College of Engineering",
    course: "Electronics",
    year: 1,
    preferredArea: "Marathahalli",
    budgetMin: 7000,
    budgetMax: 11000,
    languages: ["English", "Hindi", "Gujarati"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "NIGHT_OWL" as const,
    cleanliness: "MODERATE" as const,
    pets: false,
    studyHabits: "SOCIAL" as const,
    interests: ["Anime", "Gaming", "K-pop"],
    bio: "First-year, night owl, always got a show playing.",
  },
  {
    email: "riya.d@campus.edu",
    name: "Riya Desai",
    age: 19,
    gender: "FEMALE" as const,
    genderPreference: "ANY" as const,
    college: "National College of Engineering",
    course: "Electronics",
    year: 1,
    preferredArea: "Marathahalli",
    budgetMin: 6000,
    budgetMax: 10000,
    languages: ["English", "Hindi", "Marathi"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "NIGHT_OWL" as const,
    cleanliness: "MODERATE" as const,
    pets: false,
    studyHabits: "SOCIAL" as const,
    interests: ["Anime", "K-pop", "Art"],
    bio: "Also a first-year, big anime fan, easy budget.",
  },
  {
    email: "sahil.m@campus.edu",
    name: "Sahil Malhotra",
    age: 24,
    gender: "MALE" as const,
    genderPreference: "ANY" as const,
    college: "National College of Engineering",
    course: "Computer Science",
    year: 5,
    preferredArea: "HSR Layout",
    budgetMin: 11000,
    budgetMax: 16000,
    languages: ["English", "Hindi", "Punjabi"],
    foodPreference: "NON_VEG" as const,
    smoking: "REGULARLY" as const,
    drinking: "REGULARLY" as const,
    sleepSchedule: "NIGHT_OWL" as const,
    cleanliness: "RELAXED" as const,
    pets: true,
    studyHabits: "SOCIAL" as const,
    interests: ["Music", "Gaming", "Football"],
    bio: "Grad student, laid back about mess, loud music on weekends.",
  },
  {
    email: "vivek.n@campus.edu",
    name: "Vivek Nambiar",
    age: 22,
    gender: "MALE" as const,
    genderPreference: "ANY" as const,
    college: "National College of Engineering",
    course: "Computer Science",
    year: 3,
    preferredArea: "HSR Layout",
    budgetMin: 10000,
    budgetMax: 15000,
    languages: ["English", "Hindi", "Kannada"],
    foodPreference: "NON_VEG" as const,
    smoking: "SOMETIMES" as const,
    drinking: "REGULARLY" as const,
    sleepSchedule: "NIGHT_OWL" as const,
    cleanliness: "RELAXED" as const,
    pets: true,
    studyHabits: "SOCIAL" as const,
    interests: ["Football", "Gaming", "Music"],
    bio: "Almost a carbon copy of Rahul's vibe — should score very high against similar profiles.",
  },
  {
    email: "neha.k@campus.edu",
    name: "Neha Kulkarni",
    age: 20,
    gender: "FEMALE" as const,
    genderPreference: "FEMALE" as const,
    college: "Bengaluru Institute of Technology",
    course: "Computer Science",
    year: 2,
    preferredArea: "Koramangala",
    budgetMin: 12500,
    budgetMax: 17500,
    languages: ["English", "Hindi", "Marathi"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "EARLY_BIRD" as const,
    cleanliness: "VERY_CLEAN" as const,
    pets: false,
    studyHabits: "QUIET" as const,
    interests: ["Reading", "Yoga", "Baking"],
    bio: "Near-identical lifestyle to Aisha and Priya — good high-score test case.",
  },
  {
    email: "aditya.r@campus.edu",
    name: "Aditya Rao",
    age: 25,
    gender: "MALE" as const,
    genderPreference: "ANY" as const,
    college: "St. Xavier's College",
    course: "Finance",
    year: 5,
    preferredArea: "Whitefield",
    budgetMin: 25000,
    budgetMax: 32000,
    languages: ["English", "Telugu"],
    foodPreference: "NON_VEG" as const,
    smoking: "REGULARLY" as const,
    drinking: "REGULARLY" as const,
    sleepSchedule: "NIGHT_OWL" as const,
    cleanliness: "RELAXED" as const,
    pets: false,
    studyHabits: "SOCIAL" as const,
    interests: ["Poker", "Clubbing", "Cars"],
    bio: "High budget, night owl, heavy smoker/drinker — deliberately low-compatibility test case against the quiet/clean crowd.",
  },
  {
    email: "fatima.s@campus.edu",
    name: "Fatima Sheikh",
    age: 21,
    gender: "FEMALE" as const,
    genderPreference: "ANY" as const,
    college: "St. Xavier's College",
    course: "Psychology",
    year: 3,
    preferredArea: "Jayanagar",
    budgetMin: 8500,
    budgetMax: 12500,
    languages: ["English", "Urdu", "Hindi"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "EARLY_BIRD" as const,
    cleanliness: "VERY_CLEAN" as const,
    pets: false,
    studyHabits: "QUIET" as const,
    interests: ["Reading", "Music", "Volunteering"],
    bio: "Budget-conscious, quiet, tidy — should pair well with Divya and Ananya in Jayanagar.",
  },
  {
    email: "rohan.b@campus.edu",
    name: "Rohan Bose",
    age: 23,
    gender: "MALE" as const,
    genderPreference: "MALE" as const,
    college: "National College of Engineering",
    course: "Computer Science",
    year: 4,
    preferredArea: "Whitefield",
    budgetMin: 18500,
    budgetMax: 24500,
    languages: ["English", "Bengali", "Hindi"],
    foodPreference: "VEGAN" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "EARLY_BIRD" as const,
    cleanliness: "VERY_CLEAN" as const,
    pets: false,
    studyHabits: "QUIET" as const,
    interests: ["Fitness", "Reading", "Cooking"],
    bio: "Practically a twin of Karan and Vikram's routine — another strong high-score test case.",
  },
  {
    email: "sana.p@campus.edu",
    name: "Sana Pillai",
    age: 19,
    gender: "FEMALE" as const,
    genderPreference: "ANY" as const,
    college: "National College of Engineering",
    course: "Electronics",
    year: 1,
    preferredArea: "Marathahalli",
    budgetMin: 6500,
    budgetMax: 10500,
    languages: ["English", "Malayalam", "Hindi"],
    foodPreference: "VEG" as const,
    smoking: "NEVER" as const,
    drinking: "NEVER" as const,
    sleepSchedule: "NIGHT_OWL" as const,
    cleanliness: "MODERATE" as const,
    pets: false,
    studyHabits: "SOCIAL" as const,
    interests: ["Anime", "Gaming", "Art"],
    bio: "First-year night owl on a tight budget — should mirror Tanvi and Riya closely.",
  },
  {
    email: "imran.q@campus.edu",
    name: "Imran Qureshi",
    age: 27,
    gender: "MALE" as const,
    genderPreference: "ANY" as const,
    college: "St. Xavier's College",
    course: "MBA",
    year: 5,
    preferredArea: "Indiranagar",
    budgetMin: 30000,
    budgetMax: 40000,
    languages: ["English", "Urdu"],
    foodPreference: "NON_VEG" as const,
    smoking: "REGULARLY" as const,
    drinking: "REGULARLY" as const,
    sleepSchedule: "NIGHT_OWL" as const,
    cleanliness: "RELAXED" as const,
    pets: true,
    studyHabits: "SOCIAL" as const,
    interests: ["Networking", "Golf", "Travel"],
    bio: "Way above the typical student budget with a very different lifestyle — another good low-score contrast case.",
  },
];

async function main() {
  console.log(`Seeding ${seedProfiles.length} demo users…`);
  const passwordHash = await bcrypt.hash("password123", 10);

  for (const [i, p] of seedProfiles.entries()) {
    const listingType = i % 2 === 0 ? ("HAS_ROOM" as const) : ("NEEDS_ROOM" as const);
    const user = await prisma.user.upsert({
      where: { email: p.email },
      create: {
        email: p.email,
        passwordHash,
        emailVerified: true,
      },
      update: {},
    });

    await prisma.profile.upsert({
      where: { userId: user.id },
      create: {
        userId: user.id,
        name: p.name,
        bio: p.bio,
        age: p.age,
        gender: p.gender,
        genderPreference: p.genderPreference,
        listingType,
        college: p.college,
        course: p.course,
        year: p.year,
        city: CITY,
        preferredArea: p.preferredArea,
        budgetMin: p.budgetMin,
        budgetMax: p.budgetMax,
        languages: p.languages,
        foodPreference: p.foodPreference,
        smoking: p.smoking,
        drinking: p.drinking,
        sleepSchedule: p.sleepSchedule,
        cleanliness: p.cleanliness,
        pets: p.pets,
        studyHabits: p.studyHabits,
        interests: p.interests,
        verified: true,
        isComplete: true,
      },
      update: {
        name: p.name,
        bio: p.bio,
        age: p.age,
        gender: p.gender,
        genderPreference: p.genderPreference,
        listingType,
        college: p.college,
        course: p.course,
        year: p.year,
        city: CITY,
        preferredArea: p.preferredArea,
        budgetMin: p.budgetMin,
        budgetMax: p.budgetMax,
        languages: p.languages,
        foodPreference: p.foodPreference,
        smoking: p.smoking,
        drinking: p.drinking,
        sleepSchedule: p.sleepSchedule,
        cleanliness: p.cleanliness,
        pets: p.pets,
        studyHabits: p.studyHabits,
        interests: p.interests,
        verified: true,
        isComplete: true,
      },
    });
  }

  console.log("Seed complete. All demo accounts use password: password123");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
